apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: k8s-proj
spec:
  ports:
  - protocol: 'TCP'
    port: 3306
    targetPort: 3306
    nodePort: 30012
  type: NodePort  

  selector:
    app: mysql 
 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: k8s-proj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql  
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.28
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 3
          
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 20
      
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
