apiVersion: v1
kind: Service
metadata:
  name: nodejs-db
  namespace: k8s-proj
spec:
  ports:
  - protocol: 'TCP'
    port: 8080
    targetPort: 8080
    nodePort: 30015
  type: NodePort  

  selector:
    app: nodejs-db 
 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-db
  namespace: k8s-proj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-db  
  template:
    metadata:
      labels:
        app: nodejs-db
    spec:
      containers:
      - image: kamalaweenat/nodejs_db:2.3
        name: nodejs-db  
        ports:
        - containerPort: 8080
          name: nodejs-db      
        env:
        - name: mysql_pwd
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        envFrom:
          - configMapRef:
              name: env-configmap
              
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
          
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          
          
